version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    container_name: database
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - lemarikecil:/data/db
    ports:
      - 27017:27017
    networks:
    - sayib

  api:
    image: api
    build:
      context: api
      dockerfile: ./Dockerfile
    container_name: server
    ports:
      - 3001:3001
    networks:
    - sayib

  client:
    image: client
    build:
      context: client
      dockerfile: ./Dockerfile
    container_name: client
    depends_on:
      - api
    ports:
      - 3000:3000
    networks:
    - sayib

  nginx:
    image: nginx
    build:
      context: nginx
      dockerfile: ./Dockerfile
    container_name: nginx
    ports:
      - 80:80
    networks:
    - sayib

volumes:
  lemarikecil:
    driver: local

networks:
  sayib:
    name: sayib
    driver: bridge
